version: '3.9'

services:
  web:
    image: 10.0.0.2:5000/my_very_own_encryption
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - FLAG=${FLAG}
    ports:
      - "80:5000"
