version: '3'

services:
  webserver:
    environment:
      - FLAG=${FLAG}
    build:
      context: .
      dockerfile: DOCKERFILE
      args:
        FLAG: ${FLAG}
    ports:
      - "80:80"

